#ifndef CONFIG_H
#define CONFIG_H

#include "HRDL.h"

// #############  Pin defines ####################

#define CONTACT_SELECT_S0 17
#define CONTACT_SELECT_S1 27
#define CONTACT_SELECT_S2 22
#define CONTACT_SELECT_EN 26

#define COIL1_ENABLE 5
#define COIL2_ENABLE 6
#define COIL1_DETECT 18
#define COIL2_DETECT 19

#define RX 14
#define TX 15

#define CONTACT_TRIGGER1 23
#define CONTACT_TRIGGER2 24

#define SDA 2
#define SCL 3

#define REED_PIN 16
#define BOARD_CLOSED_PIN 4

#define H_BRIDGE1 25
#define H_BRIDGE2 7
#define H_BRIDGE3 8

#define CONTACT_POWER_ENABLE 5

// #############  Serial port defines ####################

#ifdef Q_OS_LINUX
#define SERIAL_PORT_NAME "/dev/ttyUSB0"
#else
#define SERIAL_PORT_NAME "COM5"
#endif

// #############  ADC defines ####################

#define ADC24_COIL1_VOLTAGE_CHANNEL HRDL_ANALOG_IN_CHANNEL_1
#define ADC24_COIL1_VOLTAGE_CHANNEL_IS_SINGLE_ENDED false

#define ADC24_COIL1_CURRENT_CHANNEL HRDL_ANALOG_IN_CHANNEL_10
#define ADC24_COIL1_CURRENT_CHANNEL_IS_SINGLE_ENDED true

#define ADC24_COIL2_VOLTAGE_CHANNEL HRDL_ANALOG_IN_CHANNEL_3
#define ADC24_COIL2_VOLTAGE_CHANNEL_IS_SINGLE_ENDED false

#define ADC24_COIL2_CURRENT_CHANNEL HRDL_ANALOG_IN_CHANNEL_9
#define ADC24_COIL2_CURRENT_CHANNEL_IS_SINGLE_ENDED true

#define ADC24_CONTACT12_VOLTAGE_CHANNEL HRDL_ANALOG_IN_CHANNEL_5
#define ADC24_CONTACT12_VOLTAGE_CHANNEL_IS_SINGLE_ENDED false

#define ADC24_CONTACT13_VOLTAGE_CHANNEL HRDL_ANALOG_IN_CHANNEL_7
#define ADC24_CONTACT13_VOLTAGE_CHANNEL_IS_SINGLE_ENDED false

#define ADC24_CONTACT_CURRENT_CHANNEL HRDL_ANALOG_IN_CHANNEL_11
#define ADC24_CONTACT_CURRENT_CHANNEL_IS_SINGLE_ENDED true

#endif // CONFIG_H
